import Mock from 'mockjs'

const cH = '/'
const mdmVeCarSeriesQueryListForPage = Mock.mock({
  result: '1',
  msg: '1',
  data: {
    dlrSalesReturn1: {
      result: '1',
      msg: '1',
      pageindex: 1,
      pagesize: 1000,
      pages: 1,
      records: 3,
      'rows': [
        {
          carBrandCn: '东风日产',
          carSeriesCode: 'J11',
          dlrShortName: '广州丰日店',
          carType: '奇骏',
          carConfigCn: 'TDRNLT31EWA---B-',
          shippingMethodNo: '1',
          engineNo: 'v8gwegs',
          certificateNo: 'gwehe43',
          warehouseNo: '1',
          optionalPackage: '选装包A',
          PurchaseType: '采购单类型A',
          retreatType: '经销商销退',
          carseariesCn: '奇骏',
          carsearies: 'A36',
          carColorCode: '红色',
          carIncolorCode: '暗夜黑',
          // 添加字段
          retreatNo: '2332tewr235',
          retreatDate: '2019-06-21',
          purchaseConfirmationDate: '2019-06-21',
          retreatAmount: 3534.64,
          colorPrice: 32.64,
          IncolorPrice: 334.64,
          totalPrice: 35534.64,
          purchaseAmount: 253.34,
          warehouse: '仓库A',
          documentStatus: 'PV财务结算',
          creator: '李万闯',
          dlrReviewTime: '2018-01-04 09:42:26',
          dlrReviewMan: '李万闯',
          remark: '备注1',
          vin: 'GERH2236twe523DFS',
          carDamageReturned: '在途车损',
          boutiquePrice: 154.84,
          shippingMethod: '自提 '
        },
        {
          carBrandCn: '东风日产',
          carSeriesCode: 'J11',
          dlrShortName: '广州丰日店',
          carType: '奇骏',
          carConfigCn: 'TDRNLT31EWA---B-',
          shippingMethodNo: '1',
          engineNo: 'v8gwegs',
          certificateNo: 'gwehe43',
          warehouseNo: '1',
          PurchaseType: '采购单类型A',
          retreatType: '经销商销退',
          carseariesCn: '奇骏',
          carsearies: 'A36',
          carColorCode: '红色',
          carIncolorCode: '暗夜黑',
          // 添加字段
          retreatNo: '2332tewr235',
          retreatDate: '2019-06-21',
          purchaseConfirmationDate: '2019-06-21',
          retreatAmount: 3534.64,
          colorPrice: 32.64,
          IncolorPrice: 334.64,
          totalPrice: 35534.64,
          purchaseAmount: 253.34,
          warehouse: '仓库A',
          documentStatus: 'PV财务结算',
          creator: '李万闯',
          dlrReviewTime: '2018-01-04 09:42:26',
          dlrReviewMan: '李万闯',
          remark: '备注1',
          vin: 'GERH2236twe523DFS',
          carDamageReturned: '在途车损',
          optionalPackage: '选装包A',
          boutiquePrice: 154.84,
          shippingMethod: '自提 '
        },
        {
          carBrandCn: '东风日产',
          carSeriesCode: 'J11',
          dlrShortName: '广州丰日店',
          carType: '奇骏',
          carConfigCn: 'TDRNLT31EWA---B-',
          shippingMethodNo: '1',
          engineNo: 'v8gwegs',
          certificateNo: 'gwehe43',
          optionalPackage: '选装包A',
          warehouseNo: '1',
          PurchaseType: '采购单类型A',
          retreatType: '经销商销退',
          carseariesCn: '奇骏',
          carsearies: 'A36',
          carColorCode: '红色',
          carIncolorCode: '暗夜黑',
          // 添加字段
          retreatNo: '2332tewr235',
          retreatDate: '2019-06-21',
          purchaseConfirmationDate: '2019-06-21',
          retreatAmount: 3534.64,
          colorPrice: 32.64,
          IncolorPrice: 334.64,
          totalPrice: 35534.64,
          purchaseAmount: 253.34,
          warehouse: '仓库A',
          documentStatus: 'PV财务结算',
          creator: '李万闯',
          dlrReviewTime: '2018-01-04 09:42:26',
          dlrReviewMan: '李万闯',
          remark: '备注1',
          vin: 'GERH2236twe523DFS',
          carDamageReturned: '在途车损',
          boutiquePrice: 154.84,
          shippingMethod: '自提 '
        },
        {
          carBrandCn: '东风日产',
          carSeriesCode: 'J11',
          dlrShortName: '广州丰日店',
          carType: '奇骏',
          carConfigCn: 'TDRNLT31EWA---B-',
          shippingMethodNo: '1',
          engineNo: 'v8gwegs',
          certificateNo: 'gwehe43',
          warehouseNo: '1',
          PurchaseType: '采购单类型A',
          retreatType: '经销商销退',
          carseariesCn: '奇骏',
          carsearies: 'A36',
          carColorCode: '红色',
          carIncolorCode: '暗夜黑',
          // 添加字段
          retreatNo: '2332tewr235',
          retreatDate: '2019-06-21',
          optionalPackage: '选装包A',
          purchaseConfirmationDate: '2019-06-21',
          retreatAmount: 3534.64,
          colorPrice: 32.64,
          IncolorPrice: 334.64,
          totalPrice: 35534.64,
          purchaseAmount: 253.34,
          warehouse: '仓库A',
          documentStatus: 'PV财务结算',
          creator: '李万闯',
          dlrReviewTime: '2018-01-04 09:42:26',
          dlrReviewMan: '李万闯',
          remark: '备注1',
          vin: 'GERH2236twe523DFS',
          carDamageReturned: '在途车损',
          boutiquePrice: 154.84,
          shippingMethod: '自提 '
        },
        {
          carBrandCn: '东风日产',
          carSeriesCode: 'J11',
          dlrShortName: '广州丰日店',
          carType: '奇骏',
          carConfigCn: 'TDRNLT31EWA---B-',
          shippingMethodNo: '1',
          engineNo: 'v8gwegs',
          certificateNo: 'gwehe43',
          warehouseNo: '1',
          PurchaseType: '采购单类型A',
          retreatType: '经销商销退',
          carseariesCn: '奇骏',
          carsearies: 'A36',
          optionalPackage: '选装包A',
          carColorCode: '红色',
          carIncolorCode: '暗夜黑',
          // 添加字段
          retreatNo: '2332tewr235',
          retreatDate: '2019-06-21',
          purchaseConfirmationDate: '2019-06-21',
          retreatAmount: 3534.64,
          colorPrice: 32.64,
          IncolorPrice: 334.64,
          totalPrice: 35534.64,
          purchaseAmount: 253.34,
          warehouse: '仓库A',
          documentStatus: 'PV财务结算',
          creator: '李万闯',
          dlrReviewTime: '2018-01-04 09:42:26',
          dlrReviewMan: '李万闯',
          remark: '备注1',
          vin: 'GERH2236twe523DFS',
          carDamageReturned: '在途车损',
          boutiquePrice: 154.84,
          shippingMethod: '自提 '
        },
        {
          carBrandCn: '东风日产',
          carSeriesCode: 'J11',
          dlrShortName: '广州丰日店',
          carType: '奇骏',
          carConfigCn: 'TDRNLT31EWA---B-',
          shippingMethodNo: '1',
          optionalPackage: '选装包A',
          engineNo: 'v8gwegs',
          certificateNo: 'gwehe43',
          warehouseNo: '1',
          PurchaseType: '采购单类型A',
          retreatType: '经销商销退',
          carseariesCn: '奇骏',
          carsearies: 'A36',
          carColorCode: '红色',
          carIncolorCode: '暗夜黑',
          // 添加字段
          retreatNo: '2332tewr235',
          retreatDate: '2019-06-21',
          purchaseConfirmationDate: '2019-06-21',
          retreatAmount: 3534.64,
          colorPrice: 32.64,
          IncolorPrice: 334.64,
          totalPrice: 35534.64,
          purchaseAmount: 253.34,
          warehouse: '仓库A',
          documentStatus: 'PV财务结算',
          creator: '李万闯',
          dlrReviewTime: '2018-01-04 09:42:26',
          dlrReviewMan: '李万闯',
          remark: '备注1',
          vin: 'GERH2236twe523DFS',
          carDamageReturned: '在途车损',
          boutiquePrice: 154.84,
          shippingMethod: '自提 '
        }
      ]
    }
  }
})

// 车系保存
const mdmVeCarSeriesMutationSave = Mock.mock({
  result: '1',
  msg: '',
  data: {
    dlrSalesReturn2: {
      result: '1',
      msg: '保存成功'
    }
  }
})

export default [
  {
    url: '/ly/mp/busicen/orc/graphql.do' + cH + 'v=dlrSalesReturn1',
    type: 'post',
    response: config => {
      return mdmVeCarSeriesQueryListForPage
    }
  },
  {
    url: '/ly/mp/busicen/orc/graphql.do' + cH + 'v=dlrSalesReturn2',
    type: 'post',
    response: config => {
      return mdmVeCarSeriesMutationSave
    }
  }
]
